### ISSUE TITLE
ModuleNotFoundError: No module named 'icevision.backbones'

### ISSUE THREAD

**Issue by roboserg** [Lightning-AI/lightning-flash#1351]
Using an example snippet from the README:
Icevision is the latest version from GitHub master.

![image](https://user-images.githubusercontent.com/4758917/170154700-8077d278-2569-4774-af07-d8fd70a8f611.png)
![image](https://user-images.githubusercontent.com/4758917/170154662-62a15922-44c0-4838-93d9-865cccf1e076.png)

**Comment by plutasnyy** [comment]
Hey! I took a look and it looks like the problem is with python 3.10, when downgraded to 3.7 more package versions are available and the dependencies are resolved.
In python 3.10 I was not able to install valid torch version due to some problems with torchvision/torchaudio, and got this type of error:
```
    icevision[all] 0.12.0 depends on torch<1.11 and >=1.9.0
    icevision[all] 0.11.0 depends on torch<1.11 and >=1.9.0
    icevision[all] 0.8.1 depends on torch<1.9 and >=1.7.0
    icevision[all] 0.8.0 depends on torch<1.9 and >=1.7.0
```
After downgrade, it works fine. 

The question is what next with that problem, probably depends on support version of python in lightning-flash

**Comment by plutasnyy** [comment]
Readme says we support 3.10, so we should handle it somehow, for example give additional conditional on icedata/icevision to use them in specific case, or allow using them with 3.10 (it could be blocker due to some dependencies in other packages).

I can dive deeper with this problem next week. If someone wants to take care of this sooner, it is welcome

**Comment by plutasnyy** [comment]
https://github.com/pytorch/pytorch/issues/66424 is still open, do we really support python 3.10 if pytorch does not?

**Comment by ethanwharris** [comment]
Hey @roboserg thanks for brining this to our attention and @plutasnyy thanks for your investigation! It sounds like the correct solution here is to refine our list of support Python versions, in fact I think we should only claim to support 3.7 - 3.9 as these are the versions we test against.
